### ISSUE TITLE
not an issue just curious

### ISSUE THREAD

**Issue by ukscone** [w5Mike/Lynx-Rom-Analysis#2]
Why did you choose the L014 rom rather than the davis one?

the davis/susy one is imho the "real" one as it has davis's and the at the time girlfriend Sue (susy)'s "signature in it (although i've only ever seen 1 lynx in the wild with it (mine :) )

**Comment by ukscone** [comment]
hate to tell you this as you've done a great job of the disassembly but Pete reminded me last night that we have the real rom  source (multimachine 48,96 & 128) although some seems to be updates from after Camputers went bust.

it's on Pete's filedump

http://retrogubbins.co.uk/downloads/download/20-lynx-rom-source-code

**Comment by w5Mike** [comment]
Thanks Russell - those files are great. (Pete also pointed them out on Retrowiki.es today.) 

Looking at the code comments, those seem to be described as "CP/M versions" of the ROM. Perhaps that means they are roms for the later 96k/128k machines?  They seem to include extra things such as serial support.

Anyway, it will be interesting to "compare and contrast"! My own ROM analysis is mostly a learning exercise for me. So it's all good.

Cheers,

Mike.

**Comment by ukscone** [comment]
yeah i was talking to Pete about that (the cp/m comments) and he said 48k/96k too. i was confuzzled but hey ho. They look very like the source I was given access to in 1985 for the 96k for a while by Bob Jones/Dick Greenwood (4 floppies wrapped in aluminium foil :) ) when a mod to the character set, display routines and some enhancements to the graphics and maths routines for the Arabian market was mooted. The project never came to fruition other than some handy Z80 assembly routines for maths and rtl display i wrote but did get me one of my favourite freelance gigs after a conversation about it on the London to Leicester train at 10pm on a rainy Wednesday as well as access to a speccy and a QL :)

**Comment by w5Mike** [comment]
Wow! I hadn't realised you were so close to the action, and a freelance z80 coder right back then! Very impressive. 

So, the source code looks to me to support the 48k, with conditionals for 96k and 128k. So one code base to rule them all, so to speak. I think CPM is loaded from disk, so it is just "refined" rom code for later machines (I guess) - and labelled as CPM because that arrived late in the day.

Looking at the code, there are quite a lot of differences from the original roms - like graphics code in RAM, enhanced graphics drawing routines by Ron Penrose (like the scorpion rom, I guess?). But also sections that are clearly identical.

I may fix areas of my own disassembly to resemble this code (to some extent) - by using "official" var/label names. And supplement it with some of the comments, and constants. But only if it helps understanding. Mine is more verbose, is easier to assemble than using MACRO-80! (maybe I'll need a CPM virtual machine for that?!)

 )-:  .si "yalpsid LTR" na tahw desilaer tsuj ylno ev'I .sp

**Comment by ukscone** [comment]
I was mostly a pc support, networking, COBOL & Z80 person when i was freelancing. bit of auditing, QA & proofreading/copy editing on the side
